export function generateTypeFileHeader(generatorName: string): string {
  return `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by ${generatorName}. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.
`
}
