/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-svg-to-iconify. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'virtual:local-icons' {
  export const icons: string[]
}